import test from 'node:test';
import assert from 'node:assert/strict';
import {ProjectStore} from '../src/ui/store.js';
import {beam} from './benchmarks.mjs';
const memoryStorage=()=>{const data=new Map();return {setItem:(k,v)=>data.set(k,v),getItem:k=>data.get(k)??null};};

test('Transactions are atomic on validation error',()=>{const store=new ProjectStore(beam(),{storage:null});const before=store.snapshot();assert.throws(()=>store.transact('bad',m=>{m.elements[0].section='MISSING';}));assert.equal(store.snapshot(),before);assert.equal(store.revision,0);assert.equal(store.past.length,0);});
test('Undo and redo restore the exact structural snapshot',()=>{const store=new ProjectStore(beam(),{storage:memoryStorage()});const before=store.snapshot();store.transact('resize',m=>m.nodes[1].x=4);const after=store.snapshot();assert.equal(store.revision,1);assert.equal(store.undo(),true);assert.equal(store.snapshot(),before);assert.equal(store.redo(),true);assert.equal(store.snapshot(),after);assert.equal(store.revision,3);});
test('New branch clears redo and no-op does not change history',()=>{const store=new ProjectStore(beam(),{storage:null});assert.equal(store.transact('noop',()=>{}),false);store.transact('length',m=>m.nodes[1].x=4);store.undo();store.transact('different length',m=>m.nodes[1].x=5);assert.equal(store.redo(),false);assert.equal(store.revision,3);});
test('Autosave restores a validated SI project',()=>{const storage=memoryStorage(),store=new ProjectStore(beam(),{storage});store.transact('mass',m=>m.nodes[1].mass=250);assert.equal(store.saved,true);assert.deepEqual(ProjectStore.restore(storage),store.model);});
test('Unavailable storage does not masquerade as a saved project',()=>{const store=new ProjectStore(beam(),{storage:null});let detail;store.addEventListener('change',e=>detail=e.detail);store.transact('mass',m=>m.nodes[1].mass=10);assert.equal(store.saved,false);assert.match(detail.persistenceError,/unavailable/i);});
test('Storage failure retains the edit with an explicit persistence warning',()=>{const store=new ProjectStore(beam(),{storage:{setItem(){throw new Error('Quota exceeded');}}});let detail;store.addEventListener('change',e=>detail=e.detail);store.transact('mass',m=>m.nodes[1].mass=250);assert.equal(store.model.nodes[1].mass,250);assert.equal(store.saved,false);assert.match(detail.persistenceError,/Quota/);});
test('History obeys count and byte limits',()=>{const store=new ProjectStore(beam(),{storage:null,maxHistory:2});for(let i=4;i<10;i++)store.transact('length',m=>m.nodes[1].x=i);assert.equal(store.past.length,2);assert.equal(store.undo(),true);assert.equal(store.undo(),true);assert.equal(store.undo(),false);const tiny=new ProjectStore(beam(),{storage:null,maxHistoryBytes:1});tiny.transact('mass',m=>m.nodes[1].mass=1);assert.equal(tiny.past.length,0);});
test('Corrupt persisted model is not accepted',()=>{const storage=memoryStorage();storage.setItem('stratum-frame-project-v1','{"units":"kip-ft"}');assert.equal(ProjectStore.restore(storage),null);});
