import {icon,hydrateIcons} from './icons.js';
import {quantity,unitFactor,displaySystems} from '../core/units.js';
import {emptyModel,createBuilding,uniqueId,rectangularSection,validateModel,parseProject} from '../core/model.js';
import {DOFS,LOCAL_DOFS} from '../core/elements.js';
export const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const input=(id,value,extra='')=>`<input id="${id}" value="${esc(value)}" ${extra}>`;
const opts=(items,selected)=>items.map(item=>`<option value="${esc(item.id)}" ${item.id===selected?'selected':''}>${esc(item.name||item.id)}</option>`).join('');
export class Dialogs {
  constructor(app){
    this.app=app;this.root=document.querySelector('#dialog');this.content=document.querySelector('#dialog-content');
    this.root.querySelector('#dialog-submit').onclick=()=>this.submit();
    this.root.querySelector('form').onsubmit=e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();this.submit();};
    this.root.addEventListener('click',e=>{if(e.target===this.root){const r=this.root.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)this.root.close();}});
  }
  get model(){return this.app.store.model;}
  get units(){return displaySystems[this.app.state.units];}
  val(id){return this.root.querySelector('#'+id)?.value??'';}
  checked(id){return !!this.root.querySelector('#'+id)?.checked;}
  open(title,html,apply=null,{button='Apply changes',note='Changes invalidate existing results.',wide=false}={}){
    this.apply=apply;document.querySelector('#dialog-title').textContent=title;this.content.innerHTML=html;document.querySelector('#dialog-note').textContent=note;document.querySelector('#dialog-error').textContent='';
    const b=document.querySelector('#dialog-submit');b.textContent=apply?button:'Close';b.disabled=false;this.root.style.width=wide?'min(1080px,96vw)':'';if(!this.root.open)this.root.showModal();
    this.content.scrollTop=0;hydrateIcons(this.root);
  }
  async submit(){
    const b=document.querySelector('#dialog-submit');b.disabled=true;
    try{if(this.apply)await this.apply();this.root.close();}catch(e){document.querySelector('#dialog-error').textContent=e.message;}
    finally{b.disabled=false;}
  }
  newModel(){
    this.open('Create a structural model',`<p>Generate a connected three-dimensional frame with editable stories, section assignments, rigid diaphragms and example gravity and lateral loads.</p><div class="dialog-grid"><label class="full">Project name${input('new-name','Untitled frame')}</label><label>Number of stories${input('new-stories',6,'type="number" min="1" max="16"')}</label><label>Typical story height (${this.units.length})${input('new-height',3.4/unitFactor(this.units.length))}</label><label>Bays in X${input('new-x',3,'type="number" min="1" max="8"')}</label><label>Bays in Y${input('new-y',2,'type="number" min="1" max="8"')}</label><label>X bay width (${this.units.length})${input('new-bx',6/unitFactor(this.units.length))}</label><label>Y bay width (${this.units.length})${input('new-by',6/unitFactor(this.units.length))}</label><label class="checkbox full"><input type="checkbox" id="new-diaphragms" checked> Assign a rigid horizontal diaphragm at each floor</label><label class="checkbox full"><input type="checkbox" id="new-empty"> Start with an empty model instead (definitions retained)</label></div><div class="note-box warning-box">Example loads and combinations are illustrative. They are not a site-specific loading specification or a design-code implementation.</div>`,()=>{
      const m=this.checked('new-empty')?emptyModel():createBuilding({name:this.val('new-name'),stories:Number(this.val('new-stories')),baysX:Number(this.val('new-x')),baysY:Number(this.val('new-y')),height:quantity(this.val('new-height'),'length',this.units.length),bayX:quantity(this.val('new-bx'),'length',this.units.length),bayY:quantity(this.val('new-by'),'length',this.units.length),diaphragms:this.checked('new-diaphragms')});m.name=this.val('new-name').trim()||'Untitled frame';this.app.store.replace(m,'Create model');this.app.state.storyZ=Math.max(...m.stories.map(s=>s.z));this.app.refresh(true);
    },{button:'Create model',note:'The current model remains available through Undo.'});
  }
  definition(key,title,columns,makeDefault,note='',after=null){
    let data=structuredClone(this.model[key]);
    const render=()=>{
      const body=`<p>${note}</p><div style="overflow:auto"><table class="definition-table"><thead><tr>${columns.map(c=>`<th>${esc(c.label)}</th>`).join('')}<th></th></tr></thead><tbody>${data.map((row,i)=>`<tr data-edit-row="${i}">${columns.map(c=>`<td class="${c.wide?'wide':''}">${c.options?`<select data-field="${c.key}">${opts(typeof c.options==='function'?c.options():c.options,row[c.key])}</select>`:`<input data-field="${c.key}" value="${esc(c.show?c.show(row[c.key],row):row[c.key]??'')}" ${c.readonly?'readonly':''}>`}</td>`).join('')}<td><button type="button" class="delete-row" data-remove="${i}" title="Delete row">×</button></td></tr>`).join('')}</tbody></table></div><button type="button" class="dialog-add" id="add-definition">${icon('plus',13)} Add ${esc(title.toLowerCase().replace(/s$/,''))}</button>`;
      this.content.innerHTML=body;
      this.content.querySelector('#add-definition').onclick=()=>{collect();data.push(makeDefault(data));render();};
      this.content.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{collect();data.splice(Number(b.dataset.remove),1);render();});
    };
    const collect=()=>{for(const tr of this.content.querySelectorAll('[data-edit-row]')){const row=data[Number(tr.dataset.editRow)];for(const c of columns){const v=tr.querySelector(`[data-field="${c.key}"]`).value;row[c.key]=c.parse?c.parse(v,row):v;}}};
    this.open(title,'',()=>{collect();const old=structuredClone(this.model[key]);this.app.store.transact('Edit '+title.toLowerCase(),m=>{m[key]=data;if(after)after(m,old,data);});},{wide:columns.length>6});render();
  }
  materials(){this.definition('materials','Materials',[
    {key:'id',label:'ID'},{key:'name',label:'Name',wide:true},{key:'E',label:'E (GPa)',show:v=>v/1e9,parse:v=>quantity(v,'stress','GPa')},{key:'nu',label:'Poisson ν',parse:v=>quantity(v,'dimensionless')},{key:'density',label:'Density (kg/m³)',parse:v=>quantity(v,'density','kg/m3')}
  ],rows=>({id:nextId(rows,'MAT'),name:'New elastic material',E:200e9,nu:.3,density:7850}),'Isotropic, linear elastic properties. G is derived from E and ν. Density supplies element mass; self-weight is controlled separately by each load case. Unit suffixes such as “200 GPa” are accepted.');}
  sections(){this.definition('sections','Frame sections',[
    {key:'id',label:'ID'},{key:'name',label:'Name',wide:true},{key:'material',label:'Material',options:()=>this.model.materials},
    ...[['b','Width b','m','length'],['h','Depth h','m','length'],['A','A','m2','area'],['Iy','I2','m4','inertia'],['Iz','I3','m4','inertia'],['J','J','m4','inertia']].map(([key,label,u,dim])=>({key,label:`${label} (${u})`,parse:v=>quantity(v,dim,u)}))
  ],rows=>rectangularSection(nextId(rows,'SEC'),'New 300 × 600',.3,.6,this.model.materials[0].id),'<b>Analysis uses A, I2, I3 and J directly.</b> Width and depth control the rendered section only; changing them here does not recompute stiffness. Define → Rectangular section calculates all properties together. I2 = ∫z²dA, I3 = ∫y²dA. J is the Saint-Venant torsion constant.');}
  rectangle(){this.open('Create rectangular section',`<div class="dialog-grid"><label>Section ID${input('sec-id',uniqueId(this.model,'sections','SEC'))}</label><label>Name${input('sec-name','Rectangular section')}</label><label>Width along local 2 (m)${input('sec-b','.3')}</label><label>Depth along local 3 (m)${input('sec-h','.6')}</label><label class="full">Material<select id="sec-mat">${opts(this.model.materials)}</select></label></div><div class="note-box">A = bh; I2 = bh³/12; I3 = hb³/12. J uses the standard rectangular Saint-Venant engineering approximation, with the longer side as a and shorter side as c. This is not a thin-wall or warping formulation.</div>`,()=>{const b=quantity(this.val('sec-b'),'length','m'),h=quantity(this.val('sec-h'),'length','m');if(b<=0||h<=0)throw new Error('Positive section dimensions are required.');this.app.store.transact('Create rectangular section',m=>m.sections.push(rectangularSection(this.val('sec-id').trim(),this.val('sec-name').trim(),b,h,this.val('sec-mat'))));});}
  stories(){this.definition('stories','Stories',[
    {key:'id',label:'ID'},{key:'name',label:'Story name',wide:true},{key:'z',label:`Elevation (${this.units.length})`,show:v=>v/unitFactor(this.units.length),parse:v=>quantity(v,'length',this.units.length)}
  ],rows=>({id:nextId(rows,'S'),name:'Story '+rows.length,z:Math.max(0,...rows.map(r=>r.z))+3.4}),'Changing an existing story elevation moves joints originally on that elevation. Adding or deleting a story row changes reference levels only; it does not create or delete framing. Use Draw tools or the building template for new geometry.',(m,old,rows)=>{
    const changes=old.map(s=>[s.z,rows.find(n=>n.id===s.id)?.z??s.z]);for(const n of m.nodes){const c=changes.find(([z])=>Math.abs(n.z-z)<1e-7);if(c)n.z=c[1];}m.stories.sort((a,b)=>a.z-b.z);
  });}
  grids(){this.open('Grid systems',`<p>Grid coordinates are snap/reference lines. Editing them does not move existing joints.</p><div class="dialog-grid"><label class="full">X grid coordinates (${this.units.length}), comma-separated${input('grid-x',this.model.grids.x.map(v=>v/unitFactor(this.units.length)).join(', '))}</label><label class="full">Y grid coordinates (${this.units.length}), comma-separated${input('grid-y',this.model.grids.y.map(v=>v/unitFactor(this.units.length)).join(', '))}</label></div>`,()=>{const parse=id=>this.val(id).split(',').map(v=>quantity(v.trim(),'length',this.units.length)).sort((a,b)=>a-b);this.app.store.transact('Edit grids',m=>m.grids={x:parse('grid-x'),y:parse('grid-y')});});}
  cases(){this.definition('cases','Load cases',[
    {key:'id',label:'Case ID'},{key:'name',label:'Name',wide:true},{key:'selfWeight',label:'Self-weight multiplier',parse:v=>quantity(v,'dimensionless')}
  ],rows=>({id:nextId(rows,'LC'),name:'New linear static case',selfWeight:0}),'Each case is solved independently with the same stiffness matrix. A self-weight multiplier of 1 applies −9.80665 ρA N/m in global Z to every frame. Added joint mass is inertia only; apply its gravity load explicitly.');}
  combinations(){this.definition('combinations','Load combinations',[
    {key:'id',label:'ID'},{key:'name',label:'Name',wide:true},{key:'factors',label:'CASE:factor, CASE:factor',wide:true,show:v=>Object.entries(v).map(([k,x])=>k+':'+x).join(', '),parse:v=>{const f={};for(const item of v.split(',').map(s=>s.trim()).filter(Boolean)){const a=item.split(':');if(a.length!==2)throw new Error('Use CASE:factor syntax, for example DEAD:1.2, LIVE:1.6.');f[a[0].trim()]=quantity(a[1].trim(),'dimensionless');}return f;}}
  ],rows=>({id:nextId(rows,'COMB'),name:'New linear combination',factors:Object.fromEntries(this.model.cases.slice(0,1).map(c=>[c.id,1]))}),'Linear superposition only. Factors may be positive or negative. Nested combinations, envelopes and code-generated factors are not implemented. Example combinations are illustrative.');}
  diaphragms(){this.definition('diaphragms','Rigid diaphragms',[
    {key:'id',label:'ID'},{key:'name',label:'Name',wide:true},{key:'nodes',label:'Joint IDs (comma-separated)',wide:true,show:v=>v.join(', '),parse:v=>v.split(',').map(s=>s.trim()).filter(Boolean)}
  ],rows=>({id:nextId(rows,'D'),name:'Rigid diaphragm',nodes:this.model.nodes.filter(n=>Math.abs(n.z-this.app.state.storyZ)<1e-6&&!n.support[0]&&!n.support[1]&&!n.support[5]).map(n=>n.id)}),'Exact in-plane UX, UY and RZ constraints at a horizontal floor. UZ, RX and RY remain independent. At least two distinct, coplanar joints are required. No shell stiffness, gravity slab action, semi-rigid behavior or automatic floor mass is added.');}
  supports(){
    const selected=this.app.selectedNodes(),first=selected[0];
    this.open('Assign joint restraints',`<p>Restraints are exact zero-displacement constraints in global coordinates. Select joints in a view or enter their IDs below.</p><div class="dialog-grid"><label class="full">Joint IDs${input('support-targets',selected.map(n=>n.id).join(', '),'placeholder="J1, J2, J3"')}</label></div><div class="dialog-inline"><button type="button" class="secondary-button" id="support-fixed">Fixed</button><button type="button" class="secondary-button" id="support-pinned">Pinned</button><button type="button" class="secondary-button" id="support-free">Free</button></div><div class="support-flags">${DOFS.map((d,i)=>`<label><input type="checkbox" id="support-${i}" ${first?.support[i]?'checked':''}>${d}</label>`).join('')}</div><div class="note-box">Pinned means UX, UY, UZ restrained and all rotations free. The solver reports mechanisms rather than adding stabilization. Horizontal/RZ supports cannot be assigned to rigid-diaphragm joints in this build.</div>`,()=>{const ids=this.val('support-targets').split(',').map(v=>v.trim()).filter(Boolean);if(!ids.length)throw new Error('Select or enter at least one joint.');this.app.store.transact('Assign supports',m=>{for(const id of ids){const n=m.nodes.find(n=>n.id===id);if(!n)throw new Error('Unknown joint '+id);n.support=DOFS.map((_,i)=>this.checked('support-'+i));}});});
    for(const [id,flags]of[['fixed',Array(6).fill(true)],['pinned',[true,true,true,false,false,false]],['free',Array(6).fill(false)]])this.root.querySelector('#support-'+id).onclick=()=>flags.forEach((v,i)=>this.root.querySelector('#support-'+i).checked=v);
  }
  releases(){
    const selected=this.app.selectedElements(),first=selected[0];
    this.open('Frame end releases',`<p>Released components refer to the element’s local axes. Each released end displacement becomes an independent internal DOF; stiffness and consistent mass are retained without penalty springs.</p><div class="dialog-grid"><label class="full">Frame IDs${input('release-targets',selected.map(e=>e.id).join(', '),'placeholder="F1, F2"')}</label></div><div class="release-grid"><span></span><strong>End I</strong><strong>End J</strong>${LOCAL_DOFS.map((d,k)=>`<span>${['Axial U1','Shear U2','Shear U3','Torsion R1','Bending R2','Bending R3'][k]}</span>${[k,k+6].map(i=>`<label><input type="checkbox" id="release-${i}" ${first?.releases?.[i]?'checked':''}> Release</label>`).join('')}`).join('')}</div><div class="note-box warning-box">A double-ended axial or torsional release can introduce a free member rigid-body mode. Unsupported or singular combinations are rejected by the solver. Partial-fixity springs are not included.</div>`,()=>{const ids=this.val('release-targets').split(',').map(v=>v.trim()).filter(Boolean);if(!ids.length)throw new Error('Select or enter at least one frame.');this.app.store.transact('Assign end releases',m=>{for(const id of ids){const e=m.elements.find(e=>e.id===id);if(!e)throw new Error('Unknown frame '+id);e.releases=Array.from({length:12},(_,i)=>this.checked('release-'+i));}});});
  }
  load(){
    const ns=this.app.selectedNodes(),es=this.app.selectedElements(),type=ns.length?'nodal':'udl';
    this.open('Assign structural loads',`<p>Forces are algebraic components. Negative global Z acts downward. Member point loads use a relative position strictly between 0 and 1.</p><div class="dialog-grid"><label>Load case<select id="load-case">${opts(this.model.cases,this.app.state.caseId)}</select></label><label>Load type<select id="load-type"><option value="nodal" ${type==='nodal'?'selected':''}>Joint forces / moments</option><option value="udl" ${type==='udl'?'selected':''}>Uniform member load</option><option value="point">Member point force</option></select></label><label class="full">Target <span id="load-target-label">joint / frame IDs</span>${input('load-targets',(ns.length?ns:es).map(n=>n.id).join(', '),'placeholder="Select objects or enter IDs"')}</label><label id="load-axis-label">Coordinate system<select id="load-system"><option value="global">Global X, Y, Z</option><option value="local">Local 1, 2, 3</option></select></label><label id="load-position-label">Relative position a/L${input('load-position','.5')}</label><label><span id="load-x-label">FX</span>${input('load-v0','0')}</label><label><span id="load-y-label">FY</span>${input('load-v1','0')}</label><label><span id="load-z-label">FZ</span>${input('load-v2','-10')}</label><label class="load-moment">MX (${this.units.moment})${input('load-v3','0')}</label><label class="load-moment">MY (${this.units.moment})${input('load-v4','0')}</label><label class="load-moment">MZ (${this.units.moment})${input('load-v5','0')}</label><label class="checkbox full"><input type="checkbox" id="load-replace"> Replace existing loads of this type and case on these targets</label></div>`,()=>{
      const type=this.val('load-type'),loadCase=this.val('load-case'),ids=this.val('load-targets').split(',').map(v=>v.trim()).filter(Boolean);if(!ids.length)throw new Error('Select or enter at least one target.');
      const dim=type==='udl'?'lineLoad':'force',values=Array.from({length:type==='nodal'?6:3},(_,k)=>quantity(this.val('load-v'+k),k<3?dim:'moment',k<3?this.units[dim]:this.units.moment));
      this.app.store.transact('Assign '+type+' load',m=>{for(const id of ids){if(!(type==='nodal'?m.nodes:m.elements).some(e=>e.id===id))throw new Error('Unknown '+(type==='nodal'?'joint ':'frame ')+id);if(this.checked('load-replace'))m.loads=m.loads.filter(l=>!(l.type===type&&l.case===loadCase&&(l.node===id||l.element===id)));m.loads.push({id:uniqueId(m,'loads','L'),case:loadCase,type,...(type==='nodal'?{node:id}:{element:id,system:this.val('load-system')}),...(type==='point'?{position:quantity(this.val('load-position'),'dimensionless')}:{ }),value:values});}});this.app.state.caseId=loadCase;this.app.refresh();
    },{button:'Assign loads'});
    const update=()=>{const t=this.val('load-type'),dim=t==='udl'?'lineLoad':'force';this.root.querySelector('#load-system').disabled=t==='nodal';if(t==='nodal')this.root.querySelector('#load-system').value='global';this.root.querySelector('#load-position-label').classList.toggle('hidden',t!=='point');this.root.querySelectorAll('.load-moment').forEach(el=>el.classList.toggle('hidden',t!=='nodal'));this.root.querySelector('#load-target-label').textContent=t==='nodal'?'joint IDs':'frame IDs';for(const[k,a]of[[0,'x'],[1,'y'],[2,'z']])this.root.querySelector('#load-'+a+'-label').textContent=`${t==='udl'?'q':'F'}${this.val('load-system')==='global'?a.toUpperCase():k+1} (${this.units[dim]})`;};
    this.root.querySelector('#load-type').onchange=()=>{this.root.querySelector('#load-targets').value=(this.val('load-type')==='nodal'?ns:es).map(n=>n.id).join(', ');update();};this.root.querySelector('#load-system').onchange=update;update();
  }
  loadTable(){this.definition('loads','Assigned loads',[
    {key:'id',label:'ID'},{key:'case',label:'Case',options:()=>this.model.cases},{key:'type',label:'Type',readonly:true},{key:'target',label:'Target ID',show:(_,r)=>r.node||r.element,parse:(v,r)=>{if(r.type==='nodal')r.node=v.trim();else r.element=v.trim();return undefined;}},
    {key:'system',label:'Axes',options:[{id:'global',name:'Global'},{id:'local',name:'Local'}]},
    {key:'value',label:'SI vector: N, N/m, Nm',wide:true,show:v=>v.join(', '),parse:v=>v.split(',').map(x=>quantity(x.trim(),'dimensionless'))},
    {key:'position',label:'a/L (point only)',show:v=>v??'',parse:(v,r)=>r.type==='point'?quantity(v,'dimensionless'):undefined}
  ],rows=>({id:nextId(rows,'L'),case:this.model.cases[0].id,type:'udl',element:this.model.elements[0]?.id||'',system:'global',value:[0,0,-1000]}),'This advanced table uses canonical SI numbers: joint [FX,FY,FZ,MX,MY,MZ] in N/Nm; member [q1,q2,q3] in N/m or [F1,F2,F3] in N. Use Assign Loads for dimension-aware entry in the selected display units.');}
  json(){this.open('Model JSON · advanced editor',`<p>Canonical SI units only: metres, newtons, pascals, kilograms, radians. References and dimensions are validated atomically before the project changes.</p><textarea id="json-model" class="json-editor" spellcheck="false">${esc(JSON.stringify(this.model,null,2))}</textarea>`,()=>this.app.store.replace(parseProject(this.val('json-model')),'Apply model JSON'),{wide:true,button:'Validate & apply'});}
  viewOptions(){const s=this.app.state;this.open('Display settings',`<div class="dialog-grid"><label>Deformation magnification (0 = automatic)${input('view-scale',s.deformationScale)}</label><label>Requested modes (1–24)${input('view-modes',this.model.settings.modes,'type="number" min="1" max="24"')}</label>${[['joints','Show joint markers'],['labels','Show object labels'],['grids','Show grid and story lines'],['supports','Show restraints'],['extrude','Extrude section geometry'],['snap','Snap to grids and joints']].map(([key,label])=>`<label class="checkbox"><input type="checkbox" id="view-${key}" ${s[key]?'checked':''}>${label}</label>`).join('')}<label class="checkbox full"><input type="checkbox" id="view-modal" ${this.model.settings.modal?'checked':''}> Include modal analysis in the next run</label></div><div class="note-box">Automatic magnification uses the maximum sampled computed displacement, not the actual physical scale. Modal vectors are mass-normalized; animated amplitudes are illustrative. Static interpolation includes full-span UDL and interior point-load particular solutions. Modal interpolation uses finite-element kinematics.</div>`,()=>{const magnification=quantity(this.val('view-scale'),'dimensionless');if(magnification<0)throw new Error('Magnification must be nonnegative.');s.deformationScale=magnification;for(const key of['joints','labels','grids','supports','extrude','snap'])s[key]=this.checked('view-'+key);this.app.store.transact('Analysis settings',m=>m.settings={modes:Number(this.val('view-modes')),modal:this.checked('view-modal')});this.app.refresh();},{note:'View-only changes preserve analysis results.'});}
  validate(){let warnings;try{warnings=validateModel(this.model);}catch(e){this.open('Model validation failed',`<div class="note-box warning-box">${esc(e.message)}</div>`,null,{note:'No changes were applied.'});return;}this.open('Model validation',`<div class="note-box">${icon('check',16)} <b>Geometry and data checks passed.</b><br>${this.model.nodes.length} joints, ${this.model.elements.length} frames, ${this.model.diaphragms.length} rigid diaphragms.</div><p>This checks data, positive properties, connectivity references, lengths and assignment compatibility. Global instability is checked during matrix factorization; a valid file is not proof of a stable or adequate structure.</p>${warnings.map(w=>`<div class="note-box warning-box">${esc(w)}</div>`).join('')}`,null,{note:'Run analysis for stiffness and equilibrium diagnostics.'});}
  help(){this.open('Analysis scope & working guide',`
    <div class="note-box warning-box"><b>Research / verification workbench, not a certified structural design package.</b> Do not use its outputs as the sole basis for construction, approval, or safety-critical decisions. Independent engineering review and broader validation are required.</div>
    <h3>Modeling workflow</h3><p>Create a frame template, define materials and sections, edit stories and grids, assign supports and loads, then run analysis. Click a member or joint to inspect and edit it. Shift-click adds to the selection. Draw beams by clicking two snapped points in Plan View; columns connect the active story to the story below. Coincident coordinates do not merge imported joints; intersecting members connect only through shared joint IDs.</p>
    <h3>Analysis implemented</h3><p>Linear elastic, small-displacement, prismatic 3D Euler–Bernoulli frames: axial deformation, biaxial bending and Saint-Venant torsion. Six physical DOFs per joint. Exact horizontal rigid diaphragms. Independent internal release DOFs. Full symmetric sparse assembly, reverse Cuthill–McKee reordering, diagonal equilibration and skyline LDLᵀ. No penalty stiffness. Generalized eigenanalysis uses consistent mass, inverse subspace iteration and Rayleigh–Ritz extraction.</p>
    <h3>Loads, mass & results</h3><p>Joint forces/moments, full-span uniform line loads, interior concentrated member forces, member self-weight and linear combinations. Self-weight is a load-case multiplier, not the modal mass source. Mass comes from material density plus explicit joint mass. Joint masses do not automatically add dead load. Static curves include within-element particular solutions. Member-force diagrams use section equilibrium and explicitly resolve point-load jumps.</p>
    <h3>Not implemented</h3><p>No shell or solid elements, slab/wall action, semi-rigid floors, shear-flexible Timoshenko effects, warping, offsets, springs, settlements, P–Δ, buckling, nonlinear hinges, cracked-section updates, response spectra, time history, damping, seismic/wind code generation, code checks or ETABS file interoperability. Rectangular rendering does not imply reinforced-concrete design. Non-prismatic members need explicit segmentation and assigned section properties.</p>
    <h3>Diagnostics & limits</h3><p>Scaled nonpositive/small pivots fail the static run; the pivot tolerance is 10⁻¹². Static relative force residual limit: 10⁻⁷. Modal normwise residual target: 10⁻⁸. Exact zero-stiffness, zero-mass and unforced DOFs are excluded with a warning. Modal failure is reported separately and does not discard valid static results. Maximum input: 2,000 joints, 6,000 frames, 24 requested modes; the skyline has a 24-million-coefficient memory cap. These are guardrails, not performance guarantees.</p>
    <h3>Navigation & shortcuts</h3><p><span class="help-key">B</span> beam · <span class="help-key">C</span> column · <span class="help-key">J</span> joint · <span class="help-key">M</span> move joint · <span class="help-key">Esc</span> select / cancel draw · <span class="help-key">F</span> fit · <span class="help-key">F5</span> analyze · <span class="help-key">Delete</span> delete selection · <span class="help-key">Ctrl Z / Y</span> undo / redo · <span class="help-key">Ctrl S / O</span> save / open. Right-click opens object actions. In 3D, drag empty space to orbit; Shift-drag box-selects; middle/right drag pans. In plan, drag empty space to pan. Pinch zoom and two-finger pan are supported.</p>
    <h3>Source & references</h3><p>See the bundled README.md, docs/ANALYSIS.md and docs/verification-results.json. Numerical formulation references: TU Delft’s Euler–Bernoulli beam chapter; OpenSees elasticBeamColumn documentation. Workspace conventions reference CSI’s ETABS modeling, diaphragm and release documentation. The implementation is independent and not affiliated with CSI.</p>
    `,null,{button:'Close',note:'All project data remains in this browser unless you export it.',wide:true});}
  async benchmarks(){
    this.open('Analytical verification suite','<p>Running the same solver used by the application against analytical and invariant checks…</p>',null,{note:'Live calculation · not a saved success indicator.'});
    await new Promise(r=>setTimeout(r,30));
    const {runBenchmarks}=await import('../../tests/benchmarks.mjs');const tests=runBenchmarks(),passed=tests.filter(t=>t.passed).length;
    this.open('Analytical verification suite',`<div class="note-box ${passed<tests.length?'warning-box':''}"><b>${passed} / ${tests.length} checks passed in this browser.</b> These benchmarks validate the listed cases, not general engineering suitability.</div><table class="bench-table"><thead><tr><th>Benchmark</th><th>Result</th><th>Relative error / diagnostic</th></tr></thead><tbody>${tests.map(t=>`<tr><td>${esc(t.name)}</td><td class="${t.passed?'success-text':'error-text'}">${t.passed?'PASS':'FAIL'}</td><td>${esc(t.error||t.relativeError?.toExponential(3)||t.actual||'checked')}</td></tr>`).join('')}</tbody></table>`,null,{wide:true,note:'Full tolerances and machine-readable output are included in the source archive.'});
  }
}
function nextId(rows,prefix){const ids=new Set(rows.map(r=>r.id));let i=1;while(ids.has(prefix+i))i++;return prefix+i;}
